### ISSUE TITLE
Can set Boriel ZX Basic optimization level to 4

### ISSUE THREAD

**Issue by Duefectu** [Dotneteer/kliveide#142]
In VSCode Settings can be set optimization level to 4:
"Value must be less than or equal to 3."
Boriel ZX Basic has 4 optimization levels.

Thanks for your work!

**Comment by Dotneteer** [comment]
I've fixed this issue. It will be released in v0.7.0. By then, you can use this private build:

[kliveide-vsext-0.6.0.zip](https://github.com/Dotneteer/kliveide/files/5610329/kliveide-vsext-0.6.0.zip)

(Please, rename the `.zip` file to `.vsix` so that you can install it in VS Code)

**Comment by Dotneteer** [comment]
Released in v0.7.0
