### ISSUE TITLE
ZX BASIC

### ISSUE THREAD

**Issue by rool80** [Dotneteer/kliveide#365]
Hi, thx for your kliveide. 
But I have problem.

Klive v0.9.0

I fill Zxbc Executable Path in settings.

<img width="556" alt="Snímka obrazovky 2021-11-02 o 14 37 54" src="https://user-images.githubusercontent.com/18568139/139857697-1473cc8f-41ab-4dd8-814b-96c014c2f586.png">

When I run basic example
<img width="605" alt="Snímka obrazovky 2021-11-02 o 14 38 51" src="https://user-images.githubusercontent.com/18568139/139857881-b7eaf7d6-8886-4478-97a3-88e4d6913193.png">
I get this error
<img width="500" alt="Snímka obrazovky 2021-11-02 o 14 39 14" src="https://user-images.githubusercontent.com/18568139/139857956-92ea7261-3df6-4b6e-92fc-f4d3ace0ce96.png">

What's wrong?

When I run asm example, it's OK. Only Boriel's Basic is problem.
<img width="756" alt="Snímka obrazovky 2021-11-02 o 14 40 46" src="https://user-images.githubusercontent.com/18568139/139858261-5f71e096-bd63-4db4-bb27-8614dff18ec8.png">

**Comment by Dotneteer** [comment]
ZX Basic integration is available in release [v0.11.0](https://github.com/Dotneteer/kliveide/releases/tag/v0.11.0). Here is an [article](https://dotneteer.github.io/kliveide/getting-started/try-run-zxb-code) explaining how you can use it.
