### ISSUE TITLE
Syntax somewhat differs from SpectNet IDE

### ISSUE THREAD

**Issue by hadmir** [Dotneteer/kliveide#418]
I moved my code from SpectNet IDE, but ASM syntax is little bit different in Klive. For example:
`abc equ 300 * (16 + 1)`
reports "An Expression expected", because of parenthesis. 
Also there were some other nuances that I could change in the code, like `add 5 ---> add a, 5`
Is there documentation for this new syntax?

**Comment by Dotneteer** [comment]
@hadmir, thanks for reporting this issue. When moving to Klive, I had to totally rewrite the compiler. Though I have a lot of automatic tests, there still may be issues there. The `abc equ 300 * (16 + 1)` issue must be a bug in the compiler, soon, I will look after it. Also, I check the `add a ---> add a, 5` issue, and similar ones.

**Comment by Dotneteer** [comment]
@hadmir, you can download the private build that contains the bug fixes from here: https://1drv.ms/u/s!AqpbKz19ddp5ordqGnNWFRV2Y-QAVw?e=uWe24m

Please, keep reporting any issues you find with Klive!

**Comment by hadmir** [comment]
One more thing: Used to be: `loop MAX_CHARS` now parenthesis needed: `loop (MAX_CHARS)`. But this one is easy to fix.

**Comment by Dotneteer** [comment]
@hadmir, this is the private build with the fixes for `loop`: https://1drv.ms/u/s!AqpbKz19ddp5ordzXODk2fCGQNIRVw?e=nzmLE3
I whish you a Happy New Tear!

**Comment by hadmir** [comment]
Thanks, great new year for you too!

Here is another one difference from SpectNet IDE syntax:
```
loop 8
        outerCount = $cnt
        loop outerCount
...

```
reports Identifier 'outerCount' is not defined yet. I already uninstalled SpectNet IDE and moved to klive completely, but I am like 99% sure this specific thing compiled on SpectNet IDE.

**Comment by Dotneteer** [comment]
@hadmir, thanks for reporting the newest issue! You can download the fix from here: https://1drv.ms/u/s!AqpbKz19ddp5orktBt4VacYmpUQjnA?e=BOtcYJ

**Comment by hadmir** [comment]
Tested, OK, nothing else to report, closing.
