### ISSUE TITLE
Error while creating a new Klive project

### ISSUE THREAD

**Issue by taylorza** [Dotneteer/kliveide#427]
Klive Version:  v0.11.0
Platform: Windows 11
Description: When creating a new project on a fresh installation of Klive I get the following error message `Cannot create Klive project in 'D:\Source\ZXN\Klive\app' (TypeError: Cannot read properties of null (reading 'ide'))`.

![image](https://user-images.githubusercontent.com/13187192/149039201-39ae73ac-390a-4ec3-a058-435c460b33d2.png)

**Comment by Dotneteer** [comment]
@taylorza, Thanks for reporting this issue. The community has already notified me about similar issues, and a few days ago, I created a fix for that. You can download the private build from here: https://1drv.ms/u/s!AqpbKz19ddp5orktBt4VacYmpUQjnA?e=2ewuEW

Please check if you still experience the issue!

**Comment by taylorza** [comment]
@Dotneteer, thanks I just installed it and I am able to create a new project.
