### ISSUE TITLE
Copy/paste not working on MacOS

### ISSUE THREAD

**Issue by marco-leal-zx** [Dotneteer/kliveide#438]
Copy/paste does not work on the IDE. Copy/paste inside the IDE doesn't work. Copying from somewhere else and pasting on the IDE doesn't work.Copying from the IDE and trying to paste somewhere else also doesn't work.

**Comment by Dotneteer** [comment]
@marco-leal-zx, sorry for being late with my answer. I've just learned that the Electron shell (Klive is an Electron shell app) does not support the default shortcuts on Mac. First, I assumed there was something wrong with the Monaco code editor (the one that provides the same editing experience as in VS Code). It took a lot of time to recognize the issue with the Electron shell.

This weekend, I will release the fix.

**Comment by Dotneteer** [comment]
Fixed: https://github.com/Dotneteer/kliveide/releases/tag/v0.12.2
