### ISSUE TITLE
IDE only supports .kz80.asm files as build root

### ISSUE THREAD

**Issue by marco-leal-zx** [Dotneteer/kliveide#439]
It would be great to let any other type of file be added as build root.

**Comment by Dotneteer** [comment]
@marco-leal-zx, KliveIDE supports three builders out of the box:
- The default builder (ID: "kz80-asm", currently with the ".kz80.asm" file extension)
- The Boriel's Basic builder (ID: "zxbas", currently with the ".zxbas" file extension); requires Bioriel's Basic integration.
- The assembly builder of Boriel's Basic (ID: ''"zxbasm", currently with the ".zxb.asm" file extension); requires Bioriel's Basic integration.

When you mark a file as a root builder, the IDE knows which builder (compiler) to use. KliveIDE allows using only the file extensions above; the IDE uses the extension to decide which compiler to use.

I can add a feature that uses the IDE's setting infrastructure through commands to add your custom file extensions for root builders. Nonetheless, you must associate it with a builder. I'm thinking of using settings like this:

```
set builder.ext.kz80-asm ".myExt1,.myExt2"
```

This command would allow using the `.myExt1` and `.myExt2` extensions with your project in the same way as the default ".kz80.asm".

Also, you could expand the list of accepted extensions for other compilers similarly, for example, setting new root builders for ZX BASIC:

```
set builder.ext.zxbas ".myzxb1,.myzxb2"
```

(You can invoke these commands from the interactive command window. The `set` command sets these changes into the project's `klive.project` file.)

Any comments or ideas?

**Comment by Dotneteer** [comment]
Feature added: https://github.com/Dotneteer/kliveide/releases/tag/v0.12.2
See feature description here: https://dotneteer.github.io/kliveide/getting-started/building-and-running-code#specify-additional-build-root-file-extensions
