### ISSUE TITLE
Find/Replace dialog doesn't show any icons on MacOS

### ISSUE THREAD

**Issue by marco-leal-zx** [Dotneteer/kliveide#447]
All the icons in the dialog window show up as squares:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/66039654/182444099-69cf2c27-925b-4909-acfb-c4501d7f7b3b.png">

**Comment by Dotneteer** [comment]
Marco, thanks for reporting this issue! Soon I will check it and fix is as soon as possible.

**Comment by Dotneteer** [comment]
Fixed. Will be released in v0.12.3

**Comment by Dotneteer** [comment]
Fixed and published in Release v0.12.3
