### ISSUE TITLE
The files under "code" directory not possible to edit when opening/new project with ROM Spectrum 48k mode - Klive IDE 0.12.3

### ISSUE THREAD

**Issue by Tamairon** [Dotneteer/kliveide#452]
Hello,

I testing last version of KLive IDE in Windows. I create a new project, but I try to open any file under "code" directory like a .zxbas file and it not open to be edited. Only klive.project is possible to edit, and open in the IDE.

I already configured zxbasic with zxb-reset, but IDE continues with the same problem. 

Any solution?

![Captura](https://user-images.githubusercontent.com/19364208/189662650-e91f2c0e-dc2c-483f-87c9-c8ac075b78f6.PNG)

**Comment by Tamairon** [comment]
Hello again,

I noticed that this occurs with "Spectrum 48k" ROM mode.
Regards.

**Comment by Dotneteer** [comment]
@Tamarion, thanks for reporting this issue! Let me check and fix it this weekend.

**Comment by Dotneteer** [comment]
@Tamarion, I tried to reproduce the issue you mention but I did not manage, neither on Windows nor Mac. Please, share detailed steps with me so that I can check the issue again!
