### ISSUE TITLE
New projects do not open code files in editor

### ISSUE THREAD

**Issue by Smashcat** [Dotneteer/kliveide#453]
Followed the setup and first steps text. Created new project as shown, which populates the explorer panel with files. However, clicking on the .asm or .zxbas files does nothing. They do not open in the editor. This is with version 0.12.3 on Windows.
<img width="689" alt="ss" src="https://user-images.githubusercontent.com/599579/198882395-e3c82038-e65b-418e-9cdc-316bd6a552cd.png">

**Comment by Smashcat** [comment]
Update on this. I reinstalled with the same problem so tested a few things. It seems that if Klive is opened and the emulator is then set to 128K spectrum, and then the emulator is started and 48K spectrum is chosen, then the project is re-opened, it works as normal. After this, the project will open ok with the 48K spectrum emulator chosen.

**Comment by Dotneteer** [comment]
@Smashcat, thanks for the info, I try to reproduce the issue and fix it!

**Comment by Dotneteer** [comment]
Fixed in version [v0.30.3](https://github.com/Dotneteer/kliveide/releases/tag/v0.30.3) :-)
