### ISSUE TITLE
Selecting a file from the left doesn't open it in the editor

### ISSUE THREAD

**Issue by robpearmain** [Dotneteer/kliveide#564]
<img width="1101" alt="Screenshot 2023-09-10 at 17 37 35" src="https://github.com/Dotneteer/kliveide/assets/299240/fc6255dc-8256-4247-8531-974d5cd9f39e">

If a project name has spaces in it it seems to have difficulty finding the files to display in the editor

**Comment by robpearmain** [comment]
Hello

I have tested, and the fix is working.  Well done, and thanks

Rob

**Comment by mickpr** [comment]
It still doesn't work for me - even without spaces in project directory/filenames. Could you check it again?

**Comment by Dotneteer** [comment]
@mickpr, Please give me some hints on how to reproduce and fix your issue. Which Klive version do you use (see Help|About for details)? Which platform do you use? What is the name of the folder you open? You can even send me the zipped version of the project showing the issue you mentioned.

**Comment by mickpr** [comment]
Thanks for your attention. I use latest binary (and tested previous 2 version so) in Windows (tested on Windows 10 and 11, two independent machines), and project is a single file assembly without space in filenames/directory names. Everything works ok, but I cannot open any file in editor from "project tree".  When I do "compile" and the link to the file is shown in the bottom of Your IDE - then I can click it, and the file proprely opens at the editor. If it is hopefull - I've Python 3.11 installed before.  Maybe that's a problem?
