### ISSUE TITLE
Suggestion: Saving Zoom In / Zoom Out interface size on exit

### ISSUE THREAD

**Issue by SirRickster** [Dotneteer/kliveide#645]
Amazing IDE for retro development, very pleasant to use, with only a few flaws. 

Here my two cents,
It's possible to save Zoom In / Zoom Out interface size on exit app? would be great if remember the last interface size used
At least on linux (appimage) resets to default size and it's time consuming to setup on every app launch

Also it's a bit confusing how to configure ZXBoriel compiler path. Didn't find clear documentation about it. Maybe a dialog on first use of ZXBoriel compiler asking for path and use system file selector to point to file make this easy to setup.

Cheers !!

**Comment by Dotneteer** [comment]
@SirRickster, thanks for your suggestion! I added this request to the Klive IDE backlog.

**Comment by SirRickster** [comment]
My pleasure !! El 11 des. 2023, a les 6:03, Istvan Novak ***@***.***> va escriure:﻿
@SirRickster, thanks for your suggestion! I added this request to the Klive IDE backlog.

**Comment by Dotneteer** [comment]
@SirRickster, I need a little help from you. 

1. Please check that Klive IDE saves the window sizes and positions when restarting Klive. I want to ensure this functionality works, even if the zoom factor is not saved. (On Mac and Windows, the zoom factor is saved).
2. Please help me make this documentation about ZX Basic integration better: https://dotneteer.github.io/kliveide/working-with-ide/zxb. In the long term, I will create a dialog to help with the setup, but now, I want to spend the time with something more helpful.

Thanks in advance!

**Comment by SirRickster** [comment]
@Dotneteer Hi again,

I can confirm the window size and position is saved on exit. Just tried right now and stay in place on app reload.

About documentation, I didn't see that part of the documentation last time, my apologies. After reading it, it is crystal clear and very easy to set up zxbasic.

zxbc.py tries to detect and load the Python interpreter from the env variables, so I think it will work even without specifying the path to the interpreter, but it can be useful to be able to specify as well

Ask me if I can help you on anything else !!

**Comment by Dotneteer** [comment]
Saving the zoom factor feature added: https://github.com/Dotneteer/kliveide/pull/650
I managed to test it on Linux, Mac, and Windows
It will be released soon (with other fixes and features).

**Comment by SirRickster** [comment]
Just tried. Works like a charm.

**Comment by Dotneteer** [comment]
Released in v0.30.4: https://github.com/Dotneteer/kliveide/releases/tag/v0.30.4
