### ISSUE TITLE
LAST-K malfunction

### ISSUE THREAD

**Issue by yashcherU** [Dotneteer/kliveide#652]
Very much impressed. Waiting for a complete release. Found some bug with key scanning. LAST-K shows improper code for keys with letters :

; Sample code
  .injectopt subroutine
Start:
  .model Spectrum48
  .ent 30000

KEYS   XOR   A
       LD    (23560),A
KEY_O  LD    A,(23560)
       CP    'O'
       JR    NZ,KEY_P
       LD    DE,TXT1
PRINT  LD    BC,5
       CALL  8252
       LD    A,13
       RST   16
       JR    KEYS
KEY_P  CP    'P'
       JR    NZ,KEY_Q
       LD    DE,TXT2
       JR    PRINT
KEY_Q  CP    'Q'
       JR    NZ,KEY_A
       LD    DE,TXT3
       JR    PRINT
KEY_A  CP    'A'
       JR    NZ,KEY_0
       LD    DE,TXT4
       JR    PRINT
KEY_0  CP    '0'
       JR    NZ,KEY_O
       RET

TXT1   DEFM "KEY O"
TXT2   DEFM "KEY P"
TXT3   DEFM "KEY Q"
TXT4   DEFM "KEY A"

**Comment by Dotneteer** [comment]
@yashcherU, please send me a screenshot of the issue with the keys! When trying your code, everything works fine. Pressing CAPS SHIFT + one of the Q, A, O, or P keys displays what I expect.

**Comment by yashcherU** [comment]
Thank you for the reply.
![1](https://github.com/Dotneteer/kliveide/assets/121695141/89e93da8-f609-4d03-825a-448a7ece7b41)
Please, look at the LAST-K, it shows F5 when I press 'P' as if it is the Print command expected. When I press 'O' it shows F4(=POKE) at the LAST-K and so on. Number keys work fine. I use Klive IDE version 0.30.0 at Windows 10 Pro(22H2)

**Comment by Dotneteer** [comment]
@yashcherU, thanks for the screenshot and the explanation! Now, everything is clear!

Well, it is not a bug but a feature :-) Besides kidding, this behavior is normal. When you start your injected code from the IDE, the ZX Spectrum OS is in a state where LAST_K understands the keystrokes as keyword tokens. In many cases, this behavior is unwanted. You can tell Klive this wish by adding the `.injectopt cursor` option (right after `.injectopt subroutine`).

If you do this, LAST_K will translate to letter keys and work as expected. (Of course, you should press CAPS SHIFT, as your code uses uppercase letters. To use lowercase letters, change the `CP` instructions subjects to lowercase.)

When I tried your code, I did not start it. Instead, I injected it into the machine and started it explicitly with `RANDOMIZE USR 30000`.

**Comment by yashcherU** [comment]
@Dotneteer, injected code with  RANDOMIZE USR 30000 really works fine.
Once again I added the **.injectopt cursor** after **.injectopt subroutine** as you said, still no result when trying to use the combination **"Promote to Build Root"** + **"Inject code and start the virtual machine"**

**Comment by Dotneteer** [comment]
@yashcherU, my bad!

I made a typo in my previous answer! You should write `.injectopt cursork` (with a `k` at the end) and not `.injectopt cursor`. Now, your code should work with no issues.

**Comment by yashcherU** [comment]
@Dotneteer,  thank you for your support. Now it's perfect.
Good luck at your project. KliveIDE, Spectrum Analyser and Skoolkit are becoming the most thrilling tools for me now

**Comment by Dotneteer** [comment]
@yashcherU, thanks for your commending words!

Please share your ideas with me in the future to let Klive go in the right direction! Do not hesitate to notify me privately (dotneteer@hotmail).com) if you need to do so!
