### ISSUE TITLE
Support for files with other extensions

### ISSUE THREAD

**Issue by marco-leal-zx** [Dotneteer/kliveide#768]
Is it possible to re-add support for files with other types of extensions? I tried adding the below to the project file but no luck.

  "ide": {
    "languages": {
      "kz80-asm": ".z80.asm|.z80asm|.asm"
    }
  }

**Comment by Dotneteer** [comment]
@marco-leal-zx, Thanks for your feedback!

You cannot change the built-in extensions in Klive at the moment. Nonetheless, I have a story about this feature in my backlog. I will pick it up and deliver this feature as soon as possible.

**Comment by Dotneteer** [comment]
@marco-leal-zx, I have implemented this feature in [Klive v0.32.0](https://github.com/Dotneteer/kliveide/releases/tag/v0.32.0). 

Before using it, please read [this article](https://dotneteer.github.io/kliveide/howto/file-extensions). Also, note that Klive has a new build system, so you may need to [update your project](https://dotneteer.github.io/kliveide/getting-started/creating-project#updating-old-projects).
