### ISSUE TITLE
[Linux Mint] X.org. Putting IDE window by side crashes  kliveide

### ISSUE THREAD

**Issue by Trecopt** [Dotneteer/kliveide#792]
When drag from top window KliveIDE bar to the side for put it as half-screen crashes the program, not happpen with emulator window...

https://github.com/user-attachments/assets/e394c487-d597-432c-8e0f-670ea9b36889

KliveIdeSetup-0.32.1-x86_64.AppImage

Kernel		: Linux 6.8.0-47-generic (x86_64)
Version		: #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024
C Library		: GNU C Library / (Ubuntu GLIBC 2.39-0ubuntu8.3) 2.39
Distribution		: Linux Mint 22

Processor		: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
Memory		: 24385MB (7875MB used)
Machine Type		: Desktop
Operating System		: Linux Mint 22
Date/Time		: seg 21 out 2024 22:30:06
-Display-
Resolution		: 2560x1080 pixels
OpenGL Renderer		: AMD Radeon RX 570 Series (radeonsi, polaris10, LLVM 17.0.6, DRM 3.57, 6.8.0-47-generic)
X11 Vendor		: The X.Org Foundation
-Audio Devices-
Audio Adapter		: HDA-Intel - HDA Intel PCH
Audio Adapter		: HDA-Intel - HDA ATI HDMI

**Comment by Dotneteer** [comment]
@Trecopt Thanks for signing this issue! Soon, I will try to reproduce it and then fix it.

**Comment by Dotneteer** [comment]
@Trecopt, Unfortunately, I did not manage to reproduce this issue. I use Mac OSX as my development environment and tried to use Ubuntu on Parallels. I also tried Windows  (running on Parallels) with a similar window arrangement feature.

Nonetheless, I created a new release with updated Electron shell files; perhaps this was an Electron shell issue. You can download the new release from here: https://github.com/Dotneteer/kliveide/releases/tag/v0.32.2

If the new release still does not solve the problem, I'm happy to have a call with you. If you are in, we can set up a development machine on your Mint and catch the crash message (it's easy in a development environment). That message may provide some information to help me understand the issue.

In the README, you can find my email address; please contact me.

**Comment by Trecopt** [comment]
kliveide v0.32.2 Works fine now! Scaling without crash! thank you!
