### ISSUE TITLE
New project dialog, create button is always off?

### ISSUE THREAD

**Issue by bleuge** [Dotneteer/kliveide#796]
In File>New project dialog, I fill all the fields but the create button is always off.
Am I doing something wrong?
Regards!
--
It seems the create button is off is I select the project folder, if I left it empty and fill only the project name, I can create the project.

I move it later to where I really like it to be, not a problem, or maybe I 
am doing something wrong?

**Comment by Dotneteer** [comment]
@bleuge, Please upload a screenshot to ensure I understand your issue correctly. Also, could you specify the Klive IDE version? You will find that in Help | About.

**Comment by bleuge** [comment]
Hi, just testing you last release version, 032.2
 
This is the create project dialog,
![image](https://github.com/user-attachments/assets/84491d6b-fc00-443e-b9fa-5f97fb86b95a)

It seems if a project folder is selected, the create button is disabled and the
dialog can only be cancelled.

**Comment by Dotneteer** [comment]
Thanks for the screenshot! 

The red border around the project folder means that Klive does not accept the name as a valid folder. I suspect it is a bug with the Windows version (I use Mac OS when developing Klive). **I will soon fix it.**

While it is not fixed, please try to change all backslash (`\`) to forward slash (`/`) and tell me if it helped!

**Comment by bleuge** [comment]
Editing the field and changing to forward slash don't fix it, still in red. 
But I left it empty, and found the project files where created and saved in C:\Users\_USERNAME-\KliveProjects\

So no a big problem, I keep on testing, I am testing Boriel's Basic and comparing this to ZxBasicStudio

Thanks!

**Comment by Dotneteer** [comment]
Thanks for your help. I managed to reproduce the issue, and the fix is coming in the next patch version (today)

Klive IDE is not as robust as Boriel's Basic with ZxBasicStudio, but hopefully, one day it will be :-)

**Comment by bleuge** [comment]
It seems the problem is deeper.
I used zxb-reset to configure zxbc.exe path, and it seems it worked.
But compilation didn't work: 

```
Script buildCode (with ID 3) has been started.
Start compiling vn.zxbas 
Executing C:\dev\0zx\boriel\zxbasic\zxbc.exe C:\Dropbox\00pro\00zx\basicvn/vn.zxbas --output C:\Dropbox\00pro\00zx\basicvn/vn.zxbas.bin --mmap C:\Dropbox\00pro\00zx\basicvn/vn.zxbas.lab --optimize 2 --org 32768 --heap-size 4096
Error: file 'vnstrings.zxbas' not found - C:\Dropbox\00pro\00zx\basicvn/vn.zxbas (2:1) 
Compilation failed with 1 error.
```

There is a problem with forward slashs.

Thanks!

**Comment by Dotneteer** [comment]
I will check and fix this issue, too :-)

**Comment by Dotneteer** [comment]
It seems so that it is not a slash/backslash issue. The ZXB compiler founds the `vn.zxbas` file, however, it cannot find the `vnstrings.zxbas` file. Can you send me the zipped Klive project for check?

**Comment by bleuge** [comment]
You are right! It was a mistake in my test file. It compiles and runs ok. 

I'll keep on testing, I am interested in debugging :D 
Regards

**Comment by Dotneteer** [comment]
@bleuge, here is the new release with the New project dialog fix: https://github.com/Dotneteer/kliveide/releases/tag/v0.32.3
