### ISSUE TITLE
Bug 0.4.0 - Set Tape File not working for 128

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/kliveide#91]
Set tape file does work for 48K but not for 128K files.

I tried with files from https://tzxvault.org/128k.htm

A message should pop up indicating that the tape was successfully loaded or failed to load.

**Comment by Dotneteer** [comment]
Issue fixed. To be released in 0.5.0.

**Comment by Dotneteer** [comment]
Released in 0.5.0
