### ISSUE TITLE
Bug 0.4.0 - Fast Loading Switch

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/kliveide#93]
Switching fast loading on and off does work ok before the emulation starts (either for 48k or 128k). It would be handy if it also worked after you start the emulation. 

For example, right now, if you start the emulation of 48k with standard loading times and then decide to switch to fast loading, when you type `Load ""` it will load the tape normally.

**Comment by Dotneteer** [comment]
Well, right now this behavior is intentional (it was the easiest way to implement). Nonetheless, I accept the importance of the request, and added it as a feature request to my backlog.

**Comment by Ultrahead** [comment]
Understood and thanks. The simpler (or straightforward) the UX can get, the better to reach more users

**Comment by Dotneteer** [comment]
Implemented. To be released in 0.5.0.

**Comment by Dotneteer** [comment]
Released in 0.5.0
