### ISSUE TITLE
Bug 0.4.0 (MacOSX) - Emulator windows cannot be restored

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/kliveide#94]
When closing the emulator windows with the X button on MacOSX, the active window is closed but the emulator app is not. And selecting Window >> Window on KliveIDE will not bring the closed window back.

The only way to get a new active window is to manually close the whole app and restar it.

**Comment by Dotneteer** [comment]
Issue fixed. To be released in 0.5.0.

**Comment by Dotneteer** [comment]
Released in 0.5.0
